Feature/creation long term statistic
AmelianceSkyMusic/engle pull request #30
Opened 2022-12-23 10:56 UTC by DStukalo

2022-12-25 14:42 UTC, AmelianceSkyMusic requested changes

2022-12-25 14:42 UTC, AmelianceSkyMusic commented on src/App/pages/Statistics/LongTermStat.tsx
> +/* eslint-disable prefer-destructuring */
а чого просто не використати деструктивне присвоювання?

2022-12-25 14:42 UTC, AmelianceSkyMusic commented on src/styles/pages/statistics.scss
> +			color: var(--color--h-2);
У нас нема таких змінних в css темі=)))

2022-12-25 14:42 UTC, AmelianceSkyMusic commented on src/styles/pages/statistics.scss
> +			color: var(--color--a5-0);
У нас для лінків є клас link, можеш поплясати звідти, і у нас лінки кольору --color--f1-1
Як отут https://amelianceskymusic.github.io/engle/#/login

2022-12-27 11:07 UTC, Kantor17 approved these changes

2023-05-02 14:05 UTC, merged